{% set name = "opensearch-dsl" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opensearch-dsl-{{ version }}.tar.gz
  sha256: e54ad0d754358233503e0c08e85b77dbe07d6c00babeae62c81d8cee11965ae6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opensearch-py >=1.0.0
    - python >=3.6
    - python-dateutil
    - six

test:
  imports:
    - opensearch_dsl
    - opensearch_dsl.response
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opensearch-project/opensearch-dsl-py
  summary: Python client for OpenSearch
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - chrisburr
    - rpozzi
